### ISSUE TITLE
监控直播类m3u8时无法连续下载

### ISSUE THREAD

**Issue by youngjack86** [yangwk/m3u8-downloader#12]
macOS 13.0 (22A380)
Chrome 108.0.5359.124
m3u8-downloader 3.0
当监控到 m3u8 文件后点下载可以获取当前状态下少数 .ts 片段文件（<=5个），但是无法继续监控下载同一url的全部内容。
请问大佬是设置问题还是版本限制？

**Comment by yangwk** [comment]
你好。
直播类的m3u8目前不支持，直播类的内容会变化的，需要不断去下载新内容。
目前仅支持的m3u8类型是内容不会改变的#EXT-X-PLAYLIST-TYPE:VOD
